presqt/models.py, presqt/tests/test_buddy_github_test.py
checking to see if buddy info shows up in Github about a failing test
=> testing buddy github settings/protections now with a failing test!!

config/settings/base.py, presqt/models.py, presqt/tests/test_buddy_github_check.py
Testing Buddy/Github communication.  This branch has a unit test the is intentionally meant to fail.
=> Recla buddy GitHub test ii

presqt/tests/test_buddy_python_communication.py
Testing Buddy/Github communication.
=> Recla buddy githhub communication

config/settings/base.py
Removed AUTH_USER_MODEL setting in the Settings file
=> Removed a setting attribute

README.md, presqt/api_v1/__init__.py, presqt/api_v1/helpers/function_router.py, presqt/api_v1/serializers/resource.py, presqt/api_v1/serializers/target.py, presqt/api_v1/tests/views/test_resource.py, presqt/api_v1/tests/views/test_target.py, presqt/api_v1/urls.py, presqt/api_v1/views/resource.py, presqt/api_v1/views/target.py, presqt/management/commands/validate_target_json.py
- Added Target Resources Endpoint
- Includes FunctionRouter() class for....function routing.
- N/A
- https://crcdev.atlassian.net/secure/RapidBoard.jspa?rapidView=6&projectKey=PRES&modal=detail&selectedIssue=PRES-26
**Notes**
- There's a dummy placeholder OSF function. This will be replaced once OSF gets integrated.
=> Target Resources GET endpoint

presqt/api_v1/helpers/function_router.py, presqt/api_v1/helpers/target_validation.py, presqt/api_v1/serializers/target.py, presqt/api_v1/tests/views/test_resource.py, presqt/api_v1/tests/views/test_target.py, presqt/api_v1/urls.py, presqt/api_v1/views/resource.py, presqt/api_v1/views/target.py, presqt/json_schemas/target_schema.json, presqt/management/commands/validate_target_json.py, presqt/targets.json
- Changed url paths to always say 'targets' instead of 'target'
- Added more Target JSON validation. Specifically checking that all True 'actions' have corresponding functions in FunctionRouter
- Changed ResourceCollection() validation.
- Updated targets.json to represent work done.
- N/A
- N/A
**Notes**
- N/A
=> Target Validation + URLs update

docker/django_entrypoint.sh, presqt/api_v1/utilities/io/write_file.py, presqt/api_v1/utilities/io/zip_file.py, presqt/api_v1/utilities/multiprocess/watchdog.py, presqt/api_v1/views/resource/resource_download.py, presqt/management/commands/delete_outdated_mediafiles.py, presqt/management/tests/commands/test_delete_outdated_mediafiles.py, presqt/osf/classes/base.py
Pull Request Changes for Resource Download did not get merged with the original pull request. Here they are!
=> Resource Download PR Changes

config/urls.py, presqt/api_v1/tests/views/resource/test_resource.py, presqt/api_v1/tests/views/resource/test_resource_download.py, presqt/api_v1/urls.py, presqt/api_v1/views/resource/resource.py, presqt/api_v1/views/resource/resource_download.py, presqt/management/tests/commands/test_delete_outdated_mediafiles.py
- Updated the download URLs to be more API friendly
- Moved resource download view to the resource detail class
- Made appropriate test/doc string changes.
=> Download URL/View rearrangement

config/settings/base.py
- Added FILE_UPLOAD_PERMISSIONS to base settings
=> Add FILE_UPLOAD_PERMISSIONS to settings

presqt/api_v1/serializers/resource.py, presqt/api_v1/serializers/target.py, presqt/api_v1/tests/views/resource/test_resource.py, presqt/api_v1/tests/views/resource/test_resource_collection.py, presqt/api_v1/tests/views/target/test_target.py, presqt/api_v1/utilities/__init__.py, presqt/api_v1/utilities/utils/compare_lists.py, presqt/api_v1/utilities/utils/target_actions.py
- On each endpoint there is now a links array that contains `name`, `link`, and `methods` available
- Update Serializers
- Update tests
- N/A
***Resolves Ticket***
- https://crcdev.atlassian.net/secure/RapidBoard.jspa?rapidView=5&modal=detail&selectedIssue=PRES-114
=> Branks42 API Links

presqt/api_v1/serializers/target.py, presqt/api_v1/tests/resources/targets_test.json, presqt/api_v1/tests/views/target/test_target.py, presqt/api_v1/views/target/target.py, presqt/json_schemas/target_schema.json, presqt/targets.json
- Added human readable target name to targets json and endpoints
- N/A
- https://crcdev.atlassian.net/secure/RapidBoard.jspa?rapidView=5&modal=detail&selectedIssue=PRES-121
**Notes**
- N/A
=> Human Readable Target Names

presqt/api_v1/tests/views/upload/test_upload_job.py, presqt/api_v1/views/resource/base_resource.py
- Add a link to the upload_job endpoint in the response payload for resource upload.
- Update tests.
- N/A
***Resolves Ticket***
- https://crcdev.atlassian.net/secure/RapidBoard.jspa?rapidView=5&projectKey=PRES&modal=detail&selectedIssue=PRES-122
=> Branks42 Add Upload Job Link

presqt/api_v1/tests/views/resource/test_resource.py, presqt/api_v1/tests/views/resource/test_resource_collection.py, presqt/api_v1/tests/views/upload/test_upload_job.py, presqt/targets/osf/classes/main.py, presqt/targets/osf/utilities/__init__.py, presqt/targets/osf/utilities/utils/delete_users_projects.py, requirements/base.txt
- Added checks on projects the user already has within OSF and determine whether this is a duplicate
- If it is a duplicate, we want to add to the title that the project is coming from PresQT and is duplicate #{}
- Update tests
- N/A
***Resolves Ticket***
- https://crcdev.atlassian.net/secure/RapidBoard.jspa?rapidView=5&projectKey=PRES&modal=detail&selectedIssue=PRES-126
=> Branks42 Handle Project Duplication

presqt/api_v1/tests/views/download/test_download_job.py, presqt/api_v1/utilities/utils/function_router.py, presqt/targets.json, presqt/targets/curate_nd/classes/file.py, presqt/targets/curate_nd/functions/download.py, presqt/targets/curate_nd/tests/views/download/test_download.py, presqt/targets/curate_nd/tests/views/resource/test_resource.py, presqt/targets/curate_nd/tests/views/resource/test_resource_collection.py, presqt/targets/osf/functions/download.py, presqt/targets/utilities/__init__.py, presqt/targets/utilities/tests/shared_download_test_functions.py
- Integrated CurateND download functionality
- Add test cases
- Update target info
- Minor tweaks to other download to utilize new shared function
- N/A
***Resolves Ticket***
- https://crcdev.atlassian.net/secure/RapidBoard.jspa?rapidView=5&modal=detail&selectedIssue=PRES-94
=> Branks42 Curate Download

.coveragerc, presqt/management/commands/add_new_target.py, presqt/targets.json, presqt/targets/curate_nd/functions/fetch.py, presqt/targets/osf/functions/download.py, presqt/targets/osf/functions/fetch.py, presqt/targets/osf/functions/upload.py
- Added an integration management command
- Updated target function docstrings
- N/A
- https://crcdev.atlassian.net/secure/RapidBoard.jspa?rapidView=5&modal=detail&selectedIssue=PRES-151
**Notes**
- N/A
=> Bfox6  integration mancom

presqt/targets/curate_nd/classes/file.py, presqt/utilities/utils/list_differences.py
- Now pulling md5 checksum out of characterization field to display on detail endpoint
- Refactored list_differences function
- N/A
=> Branks42 Curate md5 on Endpoint

presqt/targets/curate_nd/classes/file.py, presqt/targets/curate_nd/classes/item.py, presqt/targets/curate_nd/functions/fetch.py
- Remove sha256 from supported algorithms of Curate
- N/A
=> Remove sha256 from Curate

README.md, requirements/base.txt
- Merge Master into Develop branch to update Django
- N/A
=> Django Update

presqt/api_v1/tests/views/upload/test_upload_job.py, presqt/api_v1/views/resource/base_resource.py, presqt/api_v1/views/transfer/transfer_job.py, presqt/api_v1/views/upload/upload_job.py, presqt/targets/osf/classes/storage_folder.py, presqt/targets/osf/functions/upload.py, presqt/targets/osf/tests/views/resource/test_resource.py, presqt/targets/utilities/tests/shared_upload_test_functions.py
Changed the Upload variables files_updated/files_ignored to resources_updated/resources_ignored
=> Files Ignored/Updated changed

presqt/targets/github/functions/upload.py, presqt/targets/github/tests/views/resource/test_resource_collection.py, presqt/targets/github/utilities/helpers/create_repository.py
- Handle Repo Duplication in GitHub
- Update tests
- N/A
=> Branks42 GitHub Duplicate Repos

presqt/api_v1/views/download/download_job.py, presqt/api_v1/views/resource/base_resource.py, presqt/api_v1/views/resource/resource.py
- Changed any hard coded path creations to take advantage of os.path.join()
- N/A
- N/A
**Notes**
- N/A
=> OS Path Join Change

requirements/base.txt
- Update Django from 2.2.4 to 2.2.6 for security reasons
- Run tests
- Rebuild docker containers
=> Django Upgrade

presqt/api_v1/views/resource/base_resource.py, presqt/targets/curate_nd/functions/download.py, presqt/targets/github/functions/download.py, presqt/targets/github/functions/upload.py, presqt/targets/github/utilities/helpers/download_content.py, presqt/targets/osf/classes/storage_folder.py, presqt/targets/osf/functions/download.py, presqt/targets/osf/functions/upload.py, presqt/targets/osf/utilities/__init__.py, presqt/targets/osf/utilities/utils/osf_download_metadata.py
- Create the metadata creator functions/functionality for each target
- N/A
=> Branks42 Target Metadata Functions

presqt/api_v1/utilities/utils/function_router.py, presqt/api_v1/views/resource/base_resource.py, presqt/targets/github/functions/upload.py, presqt/targets/github/functions/upload_metadata.py, presqt/targets/github/utilities/helpers/create_repository.py, presqt/targets/osf/classes/main.py, presqt/targets/osf/functions/upload.py, presqt/targets/osf/functions/upload_metadata.py, presqt/targets/utilities/__init__.py, presqt/targets/utilities/utils/duplicate_titles.py
- Target functions for uploading PresQT metadata files
- Tweaks to base_resource
- Create duplicate title function
- Combine with bfox6__metadata branch and begin testing
- Put in how we handle metadata writing errors
=> Branks42 upload metadata

presqt/json_schemas/metadata_schema.json, presqt/json_schemas/schema_handlers.py
- Metadata schema
- Update schema_validator function
- Merge back into bfox6__metadata2 to be implemented.
=> Branks42 Metadata Schema

presqt/json_schemas/metadata_schema.json, presqt/management/commands/validate_target_json.py
- Made metadata schema more explicit (No longer allows additional parameters)
- Added required fields
- Merge back into bfox6__metadata2 branch for testing
=> Branks42 Metadata Schema Edit

presqt/api_v1/utilities/metadata/download_metadata.py, presqt/targets/curate_nd/functions/download.py, presqt/targets/github/functions/download.py, presqt/targets/github/utilities/helpers/download_content.py, presqt/targets/osf/classes/storage_folder.py, presqt/targets/osf/functions/download.py, presqt/targets/osf/utilities/utils/osf_download_metadata.py
Simplified what the download functions need to return for metadata.
=> Download Metadata Fix

presqt/api_v1/utilities/metadata/upload_metadata.py, presqt/targets/github/functions/upload_metadata.py, presqt/targets/github/tests/views/resource/test_resource_collection.py, presqt/targets/osf/functions/upload_metadata.py, presqt/targets/osf/tests/views/resource/test_resource.py
- Refactor target upload metadata functions, now only require single resource id
- Update tests
- None.
=> Branks42 Refactor Metadata Upload

docs/api_endpoints.rst, docs/conf.py, docs/index.rst, presqt/api_v1/views/download/download_job.py, presqt/api_v1/views/resource/base_resource.py, presqt/api_v1/views/resource/resource.py, presqt/api_v1/views/resource/resource_collection.py, presqt/api_v1/views/target/target.py, presqt/api_v1/views/transfer/transfer_job.py, presqt/api_v1/views/upload/upload_job.py, requirements/base.txt
- Added the API Endpoints section of documentation
- docker-compose up --build
**Notes**
- N/A
=> Documentation API Endpoints

requirements/base.txt
Added Versions for sphinx and readthedocs
=> Requirements Fix

presqt/targets/osf/functions/upload.py, presqt/targets/osf/functions/upload_metadata.py, presqt/targets/osf/tests/views/resource/test_resource.py, presqt/targets/zenodo/tests/views/resource/test_resource_collection.py
- Fixed a bug where if the resource id given was a node id on OSF, it was being ignored.
- Update tests
- N/A
=> Branks42 OSF Upload Fix

presqt/targets/github/functions/download.py, presqt/targets/github/functions/fetch.py, presqt/targets/github/tests/views/download/test_download.py, presqt/targets/github/tests/views/resource/test_resource.py, presqt/targets/github/tests/views/resource/test_resource_collection.py
- Allow users to fetch and download any public repo
- New test case for downloading a public repo
- Correct and update tests
- N/A
=> Branks42  GitHub api tweaks

presqt/api_v1/utilities/__init__.py, presqt/api_v1/utilities/utils/hash_tokens.py, presqt/api_v1/views/download/download_job.py, presqt/api_v1/views/resource/base_resource.py, presqt/api_v1/views/resource/resource.py, presqt/api_v1/views/transfer/transfer_job.py, presqt/api_v1/views/upload/upload_job.py
- Now hashing user tokens in process_info files
- Update all `<action>_job` endpoints to validate users by hashed tokens
- N/A
=> Branks42 Secure Process Info

presqt/api_v1/utilities/metadata/upload_metadata.py, presqt/targets/github/tests/views/resource/test_resource_collection.py, presqt/targets/utilities/tests/shared_upload_test_functions.py
- Metadata schema now expects an empty dict
- Update tests
- N/A
=> Correct bug in upload_source_metadata

docs/web_services.rst
Fixed json formatting in web_services
=> Docs Update

presqt/api_v1/serializers/target.py, presqt/api_v1/tests/resources/transfer_targets_test.json, presqt/api_v1/tests/views/resource/test_resource.py, presqt/api_v1/tests/views/resource/test_resource_collection.py, presqt/api_v1/tests/views/target/test_target.py, presqt/api_v1/tests/views/transfer/test_transfer_job.py, presqt/api_v1/utilities/__init__.py, presqt/api_v1/utilities/depth_helpers/finite_depth_upload.py, presqt/api_v1/utilities/fixity/get_or_create_hashes_from_bag.py, presqt/api_v1/utilities/metadata/upload_metadata.py, presqt/api_v1/utilities/validation/target_validation.py, presqt/api_v1/views/resource/base_resource.py, presqt/json_schemas/target_schema.json, presqt/targets.json, presqt/targets/curate_nd/tests/views/download/test_download.py, presqt/targets/curate_nd/tests/views/resource/test_resource.py, presqt/targets/curate_nd/tests/views/resource/test_resource_collection.py, presqt/targets/osf/functions/upload.py, presqt/targets/osf/tests/views/resource/test_resource.py, presqt/targets/zenodo/functions/upload.py, presqt/targets/zenodo/tests/views/resource/test_resource.py, presqt/targets/zenodo/tests/views/resource/test_resource_collection.py
- Create finite depth upload helper function.
- If a target is moving resources to a target with finite depth, we are zipping what is being moved.
- Update how metadata is working for finite targets.
- Metadata for files at source now inside zip, and created metadata file is related to the zip itself.
- Created transfer target validation function to ensure targets allow transfer from other target involved in the action.
- Update Zenodo tests.
- Update API tests.
- Created tests for transfer functionality.
- N/A
=> Infinite Structure Refactor

docs/api_endpoints.rst, presqt/api_v1/tests/views/upload/test_upload_job.py, presqt/api_v1/utilities/__init__.py, presqt/api_v1/utilities/depth_helpers/finite_depth_upload.py, presqt/api_v1/utilities/validation/structure_validation.py, presqt/api_v1/views/resource/base_resource.py, presqt/targets/github/functions/upload.py, presqt/targets/osf/functions/upload.py
- Create structure_validation function to check structure of resource to upload is valid.
- Remove structure checks from target functions.
- Update tests.
- N/A
=> Branks42 Check Directory Format

docs/api_endpoints.rst, docs/target_integration.rst, presqt/api_v1/utilities/__init__.py, presqt/api_v1/utilities/validation/search_validator.py, presqt/api_v1/views/resource/resource_collection.py, presqt/targets/curate_nd/functions/fetch.py, presqt/targets/github/functions/fetch.py, presqt/targets/github/tests/views/resource/test_resource_collection.py, presqt/targets/osf/functions/fetch.py, presqt/targets/zenodo/functions/fetch.py
- Update GitHub fetch function to allow for search
- Update ResourceCollection view to check for search parameters
- Create search_validation function
- Update GitHub tests
- Update all target functions to accept the search_parameter......parameter
- N/A
=> Branks42  GitHub search

presqt/targets/curate_nd/classes/base.py, presqt/targets/curate_nd/classes/file.py, presqt/targets/curate_nd/classes/main.py, presqt/targets/curate_nd/functions/download.py, presqt/targets/curate_nd/functions/fetch.py
- Implement CurateND search functionality.
- Note: Tests will need to be made and updated once we point to Curate's prod servers.
- N/A
=> Integrate CurateND search functionality

presqt/targets/osf/classes/main.py, presqt/targets/osf/functions/fetch.py, presqt/targets/osf/tests/views/resource/test_resource_collection.py
- Implement OSF search functionality.
- Update and write tests
- N/A
=> Branks42 OSF Search

config/nginx/snippets/ssl-params.conf
- Remove duplicate headers
- N/A
=> Branks42 Security

README.md, docs/api_endpoints.rst, docs/index.rst, docs/target_integration.rst
- Update docs with search info
- N/A
=> Update documentation with search info

presqt/management/commands/add_new_target.py
- Update management command with search_parameter
- N/A
=> Update management command with search_parameter

config/settings/development.py, requirements/base.txt
- Upgrade to Django 3
- Upgrade to djangorestframework 3.10.3
- Upgrade to django-cors-headers 3.2.0
- Rebuild docker containers
=> Branks42 Django 3

docs/api_endpoints.rst, docs/authentication_authorization.rst, docs/resources.rst
- Update documentation to remove references to localhost
- N/A
=> Update docs to replace `localhost` with Prod server

presqt/targets/curate_nd/classes/main.py
- Update CurateND error handling
- N/A
=> Update token error for Curate

presqt/api_v1/views/resource/resource_collection.py, presqt/targets/osf/tests/views/resource/test_resource_collection.py
- Update search if `title` is left blank
- Update CurateND error handling
- Add test
- N/A
=> Update Search if Title is Empty

presqt/targets/zenodo/functions/download.py, presqt/targets/zenodo/functions/fetch.py, presqt/targets/zenodo/tests/views/download/test_download.py, presqt/targets/zenodo/tests/views/resource/test_resource.py, presqt/targets/zenodo/tests/views/resource/test_resource_collection.py, presqt/targets/zenodo/utilities/__init__.py, presqt/targets/zenodo/utilities/helpers/download_helper.py, presqt/targets/zenodo/utilities/helpers/fetch_helpers.py
- Add search functionality and ability to pull public projects
- Update fetch function for detail for ability to pull public projects
- Update download function to be able to DL public projects
- N/A
=> Branks42 Zenodo Upgrades

presqt/api_v1/tests/views/download/test_download_job.py, presqt/targets/osf/classes/main.py, presqt/targets/osf/tests/views/resource/test_resource.py
- Files are now showing up when searching
- Double OSFStorage bug squished
- N/A
**Notes**
- N/A
=> Search Files Bug

docs/under_development.rst
Added an Under Development page to Read The Docs
=> RTD Under Development

presqt/targets/curate_nd/classes/base.py, presqt/targets/curate_nd/classes/main.py, presqt/targets/curate_nd/functions/fetch.py, presqt/targets/osf/classes/base.py, presqt/targets/osf/functions/fetch.py, presqt/targets/osf/tests/views/resource/test_resource_collection.py, presqt/targets/utilities/utils/async_functions.py
- Limit search results for targets to only the first page to avoid too many request errors returned by the targets
- Add error handling in async function if we get those timeouts
- Add and update tests
- N/A
=> Branks42  search bug

presqt/targets/github/functions/download.py, presqt/targets/github/functions/fetch.py, presqt/targets/github/functions/upload.py, presqt/targets/github/tests/views/download/test_download.py, presqt/targets/github/tests/views/resource/test_resource.py, presqt/targets/github/tests/views/resource/test_resource_collection.py, presqt/targets/github/utilities/helpers/validation_check.py, presqt/targets/zenodo/functions/download.py, presqt/targets/zenodo/functions/fetch.py, presqt/targets/zenodo/functions/upload.py, presqt/targets/zenodo/tests/views/download/test_download.py, presqt/targets/zenodo/tests/views/resource/test_resource.py, presqt/targets/zenodo/tests/views/resource/test_resource_collection.py, presqt/targets/zenodo/utilities/helpers/validation_check.py
- Change token authorization error messages for consistency across all partners
- Update tests...
- N/A
=> Branks42 Consistent Token Error Messages

config/nginx/conf.d/qa_local.conf
- Nginx redirects homepage to UI
- Nada
=> Branks42 UI Homepage

requirements/base.txt
- Upgrade Django to 3.0.1
- Rebuild containers
=> Hotfix Django Upgrade

presqt/management/commands/delete_outdated_mediafiles.py
- Tweak management command slightly so if it is run during development we clear the volume of all mediafiles
- N/A
=> Branks42 delete_oudated_mediafiles Update

requirements/base.txt
- Bump django to 3.0.3
- Rebuild containers
=> Bump django

docs/developer_notes.rst, docs/development_environment_setup.rst
- Add documentation about Cron container
- N/A
=> Branks42 Cron Docs

presqt/api_v1/views/download/download_job.py, presqt/api_v1/views/transfer/transfer_job.py, presqt/api_v1/views/upload/upload_job.py
=> Cancel Endpoint 2 Electric Boogaloo

presqt/targets/curate_nd/classes/main.py
- Implement a better way of grabbing the CurateND container ID.
- N/A
=> Branks42 Curate Container ID

presqt/api_v1/tests/views/transfer/test_transfer_job.py, presqt/api_v1/tests/views/upload/test_upload_job.py, presqt/api_v1/utilities/validation/structure_validation.py, presqt/api_v1/views/resource/base_resource.py, presqt/targets/github/tests/views/resource/test_resource_collection.py, presqt/targets/zenodo/tests/views/resource/test_resource_collection.py
- PRESQT_FTS_METADATA.json can no longer be transferred by itself
=> Restricted transfer from metadata file

docs/api_endpoints.rst, presqt/api_v1/tests/views/download/test_download_job.py, presqt/api_v1/tests/views/upload/test_upload_job.py, presqt/api_v1/urls.py, presqt/api_v1/views/download/download_job.py, presqt/api_v1/views/resource/resource.py, presqt/targets/github/tests/views/download/test_download.py, presqt/targets/zenodo/tests/views/download/test_download.py
- Added an endpoint for getting the JSON data of a successful download
- New endpoint piggybacks off /downloads/<ticket_number>/ by adding an extra parameter
- /downloads/<ticket_number>.json/ gets JSON data
- /downloads/<ticket_number>.zip/ gets ZIP file
- Updated tests and docs accordingly
=> Download JSON

presqt/management/tests/commands/test_delete_outdated_mediafiles.py
- Tests needed to be updated after development mode was added to command
- N/A
=> Fix delete_outdated_mediafiles tests

docs/index.rst, docs/under_development.rst, docs/user_notes.rst, docs/web_services.rst
- Added a User Notes section for transfer details
- Updated Under Development
=> User Notes

presqt/api_v1/views/download/download_job.py, presqt/api_v1/views/transfer/transfer_job.py, presqt/api_v1/views/upload/upload_job.py
- Use kill() instead of terminate()
- This gets rid of the server lag while canceling
- N/A
=> Bbois Kill Process

docs/api_endpoints.rst, presqt/targets/github/functions/fetch.py, presqt/targets/zenodo/functions/fetch.py
- Search results now ordered by the date they were modified
- Only supported by partners who support it....
-N/A
=> Order Search By Date

presqt/api_v1/urls.py, presqt/api_v1/views/service/eaasi/download.py, presqt/api_v1/views/service/eaasi/proposal.py
- Added EaaSI API endpoints and functionality
=> EaaSI Integration

presqt/api_v1/views/service/eaasi/proposal.py
- Added failure handling if EaaSI fails on their end
=> Proposal Failure

presqt/api_v1/tests/views/transfer/test_transfer_job.py, presqt/api_v1/utilities/utils/get_action_message.py, presqt/targets/utilities/tests/shared_upload_test_functions.py
- Changed Fixity Failed Message
=> Failed Fixity Message

presqt/api_v1/utilities/validation/search_validator.py, presqt/api_v1/views/resource/resource_collection.py, presqt/json_schemas/target_schema.json, presqt/specs/targets.json, presqt/targets/curate_nd/classes/base.py, presqt/targets/curate_nd/functions/fetch.py, presqt/targets/github/functions/fetch.py, presqt/targets/github/tests/views/resource/test_resource_collection.py, presqt/targets/osf/functions/fetch.py, presqt/targets/osf/tests/views/resource/test_resource_collection.py, presqt/targets/zenodo/functions/fetch.py, presqt/targets/zenodo/tests/views/resource/test_resource_collection.py
- Added "search_parameters" to targets.json
- Updated JSON schema
- Implemented 'general' search for CurateND
- Implemented 'general' search for Zenodo
- Implemented 'general' and 'author' search for GitHub
- Implemented 'author' search for OSF
- Updated tests
- N/A
=> Branks42 Author/General Search

docs/api_endpoints.rst
=> Filtering Docs

docs/target_integration.rst
- Added search docs to target integration
=> Search Docs

docs/index.rst, presqt/api_v1/utilities/utils/function_router.py, presqt/specs/targets.json, presqt/targets/gitlab/functions/download.py, presqt/targets/gitlab/tests/views/download/test_download.py, presqt/targets/gitlab/utilities/__init__.py, presqt/targets/gitlab/utilities/download_content.py, presqt/targets/gitlab/utilities/gitlab_paginated_data.py
- Added GitLab download functionality
- Update targets.json
- New tests
- N/A
=> Branks42 GitLab Download

presqt/targets/osf/functions/upload.py
- Remove unused/unnecessary code
- N/A
=> Branks42 OSF File Hashes

presqt/api_v1/serializers/resource.py, presqt/targets/gitlab/tests/views/resource/test_resource.py
- Update get_links in serializer
- Update tests
- N/A
=> Branks42 Gitlab Links

presqt/api_v1/serializers/target.py, presqt/api_v1/tests/views/resource/test_resource_collection.py, presqt/api_v1/tests/views/target/test_target.py, presqt/api_v1/utilities/utils/get_action_message.py
- Add a metadata error message to fixity-less targets
- Fixed some tests that hadn't been updated
- N/A
=> Branks42 Metadata Action Message Bug

config/settings/development.py, config/settings/qa.py, requirements/development.txt, requirements/qa.txt
Logging to graylog.
Also, logging to console.
On QA and dev.
=> Rocky  logging

presqt/targets/curate_nd/functions/download.py
- Fixed a metadata bug that turned out to be a CurateND download bug caught via metadata. Yay!
=> Metadata Fix

.gitignore, django.dockerfile, docs/api_endpoints.rst, docs/target_integration.rst, presqt/api_v1/__init__.py, presqt/api_v1/serializers/target.py, presqt/api_v1/tests/resources/targets_test.json, presqt/api_v1/tests/resources/transfer_targets_test.json, presqt/api_v1/tests/views/status/test_status.py, presqt/api_v1/tests/views/target/test_target.py, presqt/api_v1/urls.py, presqt/api_v1/views/status/status.py, presqt/api_v1/views/target/target.py, presqt/json_schemas/target_schema.json, presqt/management/commands/add_new_target.py, presqt/specs/targets.json
* Created `status/` endpoint
* updated tests and documentation
=> Rocky  status endpoint

presqt/targets/github/functions/upload.py
- Fixed the problem where no contents were getting uploaded if the github repo being uploaded had parenthesis in it
=> Fixed Github Parenthesis Bug

presqt/targets/github/functions/fetch.py
=> File ID bug if parenthesis exist

presqt/api_v1/views/status/status.py
=> Update status endpoint with readable_name

presqt/api_v1/tests/views/target/test_target.py, presqt/api_v1/urls.py, presqt/api_v1/utilities/__init__.py, presqt/api_v1/utilities/utils/function_router.py, presqt/api_v1/utilities/utils/keyword_enhancer.py, presqt/api_v1/views/resource/resource_keywords.py, presqt/json_schemas/target_schema.json, presqt/specs/services.json, presqt/specs/targets.json, presqt/targets/curate_nd/functions/keywords.py, presqt/targets/github/functions/fetch.py, presqt/targets/github/functions/keywords.py, presqt/targets/github/tests/views/resource/test_keywords.py, presqt/targets/gitlab/functions/keywords.py, presqt/targets/gitlab/tests/views/resource/test_keywords.py, presqt/targets/osf/functions/keywords.py, presqt/targets/osf/tests/views/resource/test_keywords.py, presqt/targets/zenodo/functions/keywords.py, presqt/targets/zenodo/tests/views/resource/test_keywords.py
- New Keywords Endpoint
- GET/POST
- OSF keywords/upload_keywords functions
- CurateND keywords function
- GitLab keywords/upload_keywords functions
- GitHub keywords/upload_keywords functions
- Zenodo keywords/upload_keywords functions
- Update targets.json and schema
- N/A
=> Branks42 Keywords Endpoint

presqt/api_v1/views/resource/resource_keywords.py, presqt/targets/github/tests/views/resource/test_keywords.py, presqt/targets/gitlab/tests/views/resource/test_keywords.py, presqt/targets/osf/tests/views/resource/test_keywords.py, presqt/targets/zenodo/tests/views/resource/test_keywords.py
- Enhancements now visible on the GET
- Update tests
- N/A
=> Enhancement displayed on GET

presqt/api_v1/views/resource/resource_keywords.py, presqt/targets/github/tests/views/resource/test_keywords.py, presqt/targets/gitlab/tests/views/resource/test_keywords.py, presqt/targets/osf/tests/views/resource/test_keywords.py, presqt/targets/zenodo/tests/views/resource/test_keywords.py
- POST request now takes body data
- Update tests
- N/A
=> New POST keyword functionality

presqt/api_v1/views/resource/base_resource.py, presqt/targets/osf/tests/views/resource/test_resource.py
- Fixed but that was occurring when uploading a single file in a zip
=> Upload Bug

presqt/api_v1/utilities/utils/keyword_enhancer.py
- Removed duplicate entries from enhancements
- N/A
=> Branks42 No Keyword Duplicates

presqt/api_v1/views/resource/resource_keywords.py, presqt/targets/github/tests/views/resource/test_keywords.py, presqt/targets/zenodo/tests/views/resource/test_keywords.py
***Work Completed.....Most of these changes were pushed directly to develop......whoops***
- Update Keyword POST to update or create new metadata file
- Update and write new tests
- N/A
=> Branks42 Update POST Keywords

presqt/specs/targets.json, presqt/targets/github/functions/fetch.py, presqt/targets/github/tests/views/resource/test_resource_collection.py, presqt/targets/osf/functions/fetch.py, presqt/targets/osf/tests/views/resource/test_resource_collection.py, presqt/targets/zenodo/functions/fetch.py, presqt/targets/zenodo/tests/views/resource/test_resource_collection.py
- Keyword search has been added to partner functions if partner supports keyword search
- Update tests
- Minor Zenodo fetch refactor
- N/A
=> Branks42 Keyword Search

presqt/targets/zenodo/functions/upload.py, presqt/targets/zenodo/tests/views/resource/test_resource_collection.py
- Fix bug where resources_ignored/resources_updated were not being handled on Zenodo
- Write tests
- N/A
=> Branks42 Zenodo Update/Ignore

presqt/api_v1/utilities/depth_helpers/finite_depth_upload.py, presqt/api_v1/utilities/keyword_enhancement/update_targets_keywords.py, presqt/api_v1/views/resource/base_resource.py, presqt/api_v1/views/resource/resource_keywords.py, presqt/json_schemas/metadata_schema.json
- Added a more detailed key to FTS metadata
=> Added Details to Metadata

presqt/api_v1/views/resource/resource_keywords.py, presqt/targets/osf/tests/views/resource/test_keywords.py, presqt/targets/zenodo/tests/views/resource/test_keywords.py
- Removed BaseResource
- Adjusted error messages
=> Refactor Keyword Function

presqt/targets/github/functions/keywords.py, presqt/targets/github/tests/views/resource/test_keywords.py, presqt/targets/gitlab/functions/keywords.py, presqt/targets/gitlab/tests/views/resource/test_keywords.py, presqt/targets/osf/functions/keywords.py, presqt/targets/osf/tests/views/resource/test_keywords.py, presqt/targets/zenodo/functions/keywords.py, presqt/targets/zenodo/tests/views/resource/test_keywords.py
- GET keyword functions now also check the project for FTS Metadata keywords
- Update tests
- N/A
=> Branks42 FTS Enhancement

presqt/api_v1/views/resource/base_resource.py, presqt/api_v1/views/resource/resource_keywords.py
-Added PresQT to metadata details
=> Added PresQT to metadata details

presqt/api_v1/views/resource/base_resource.py, presqt/api_v1/views/transfer/transfer_job.py
- Resource IDs now in Transfer payload
- N/A
=> Branks42 Resource IDs

presqt/api_v1/views/resource/resource_keywords.py
- Initial keys in enhancement payload
- N/A
=> Branks42 Initial Keys

presqt/api_v1/utilities/__init__.py, presqt/api_v1/utilities/keyword_enhancement/suggest_keywords.py, presqt/api_v1/utilities/keyword_enhancement/update_targets_keywords.py, presqt/api_v1/views/resource/base_resource.py
=> Initial Keywords are Part of Transfer

docs/web_services.rst, presqt/api_v1/tests/views/transfer/test_transfer_job.py, presqt/api_v1/utilities/keyword_enhancement/update_targets_keywords.py, presqt/api_v1/utilities/metadata/create_fts_metadata.py, presqt/api_v1/utilities/metadata/download_metadata.py, presqt/api_v1/utilities/metadata/upload_metadata.py, presqt/api_v1/views/resource/base_resource.py, presqt/api_v1/views/resource/resource_keywords.py, presqt/json_schemas/metadata_schema.json, presqt/targets/github/functions/keywords.py, presqt/targets/github/functions/upload_metadata.py, presqt/targets/github/tests/views/resource/test_resource.py, presqt/targets/gitlab/functions/keywords.py, presqt/targets/gitlab/functions/upload_metadata.py, presqt/targets/gitlab/tests/views/resource/test_resource.py, presqt/targets/osf/functions/keywords.py, presqt/targets/osf/functions/upload_metadata.py, presqt/targets/osf/tests/views/resource/test_resource.py, presqt/targets/zenodo/functions/keywords.py, presqt/targets/zenodo/functions/upload_metadata.py, presqt/targets/zenodo/tests/views/resource/test_resource_collection.py
=> allEnhancedKeywords is now presqtKeywords

presqt/api_v1/utilities/__init__.py, presqt/api_v1/utilities/validation/get_keyword_support.py, presqt/api_v1/views/resource/base_resource.py
- Fixed a keyword bug that occurred when transferring to nested folder
- Added functionality for transferring when a target involved doesn't have keyword abilities
=> Keyword Fix

presqt/specs/targets.json, presqt/targets/figshare/functions/fetch.py, presqt/targets/figshare/tests/views/resource/test_resource_collection.py, presqt/targets/figshare/utilities/get_figshare_project_data.py
- Added FigShare ID search.
- Added tests.
- N/A
=> Branks42 FigShare Search

presqt/api_v1/utilities/utils/function_router.py, presqt/specs/targets.json, presqt/targets/figshare/functions/fetch.py, presqt/targets/figshare/tests/views/resource/test_resource.py, presqt/targets/figshare/tests/views/resource/test_resource_collection.py, presqt/targets/figshare/utilities/get_figshare_project_data.py
- Update targets.json
- New fetch function for details
- Update function router
- New tests
- N/A
=> Branks42 Figshare Detail

presqt/api_v1/utilities/utils/function_router.py, presqt/specs/targets.json, presqt/targets/figshare/functions/download.py, presqt/targets/figshare/functions/fetch.py, presqt/targets/figshare/tests/views/download/test_download.py, presqt/targets/figshare/tests/views/resource/test_resource.py, presqt/targets/figshare/tests/views/resource/test_resource_collection.py, presqt/targets/figshare/utilities/helpers/download_content.py, presqt/targets/figshare/utilities/validation_check.py
- Update targets.json
- Download functions
- Added download functions to function_router
- New download tests
- Update old tests to include download links
- N/A
=> Branks42 Figshare Download

docs/api_endpoints.rst, docs/target_integration.rst, presqt/api_v1/utilities/utils/keyword_enhancer.py, presqt/api_v1/views/resource/resource_keywords.py, presqt/targets/github/tests/views/resource/test_keywords.py, presqt/targets/gitlab/tests/views/resource/test_keywords.py, presqt/targets/osf/tests/views/resource/test_keywords.py, presqt/targets/zenodo/tests/views/resource/test_keywords.py
- Updated keyword payloads to fix bugs
=> Keyword Bugs

presqt/targets/zenodo/functions/keywords.py
- Fixed bug where Zenodo Keyword enhancement blew up for public projects
- N/A
=> Bbois Zenodo Keywords Bug

presqt/api_v1/utilities/utils/function_router.py, presqt/specs/targets.json, presqt/targets/figshare/functions/keywords.py, presqt/targets/figshare/tests/views/resource/test_keywords.py
- Fetch keywords for articles (no support for projects/files)
- New tests
- Update targets.json
- N/A
=> Figshare keywords fetch

presqt/targets/figshare/functions/keywords.py
- Now when enhancing keywords for a Figshare project it will simply update the metadata file.
=> Figshare Project KW Functionality

presqt/targets/github/functions/download.py
- Fixed the error occurring when transferring a Github Folder
=> Github Folder Transfer Bug

config/cron/crontabs/production.crontab, presqt/api_v1/views/resource/base_resource.py, presqt/api_v1/views/resource/resource.py
- Expiration of actions is now after 5 hours instead of 5 days, this should reduce server bloat
- N/A
=> Bbois New Expiration

docker/django_entrypoint.sh
- Upped Gunicorn Timeout to 200 seconds
=> Upped Gunicorn Timeout

presqt/api_v1/utilities/metadata/download_metadata.py, presqt/api_v1/views/resource/base_resource.py
* compacted if test
* refactored metadata validation
=> Download refactor pt 1

django.dockerfile, docker/django_entrypoint.sh, presqt/targets/curate_nd/functions/download.py, presqt/targets/figshare/functions/download.py, presqt/targets/github/functions/download.py, presqt/targets/gitlab/functions/download.py, presqt/targets/osf/classes/base.py, presqt/targets/osf/classes/main.py, presqt/targets/osf/functions/download.py, presqt/targets/utilities/utils/async_functions.py, presqt/targets/zenodo/functions/download.py
-Upped guincorn timeout to 600 seconds
-Added new event loop declaration
-OSF now skips forbidden resources
=> Fixed Server Issues

announcements.json, config/nginx/conf.d/development_local.conf, docker-compose.yml
-Added announcements.txt file
- Exposed file to nginx
=> Serve Announcment File

docs/authentication_authorization.rst, docs/resources.rst, docs/web_services.rst
- Update docs to open links in new tabs
- N/A
=> Branks42 New Tab Links

docs/qa.rst
-Added bugs section in QA docs
=> Known Bugs Docs

docs/target_integration.rst, presqt/api_v1/utilities/__init__.py, presqt/api_v1/utilities/utils/page_links.py, presqt/api_v1/views/resource/resource_collection.py, presqt/targets/curate_nd/functions/fetch.py, presqt/targets/curate_nd/utilities/__init__.py, presqt/targets/curate_nd/utilities/utils/get_page_numbers.py, presqt/targets/figshare/functions/fetch.py, presqt/targets/github/functions/fetch.py, presqt/targets/github/utilities/helpers/get_page_numbers.py, presqt/targets/gitlab/functions/fetch.py, presqt/targets/gitlab/utilities/get_page_numbers.py, presqt/targets/gitlab/utilities/gitlab_paginated_data.py, presqt/targets/osf/functions/fetch.py, presqt/targets/osf/utilities/utils/get_page_numbers.py, presqt/targets/zenodo/functions/fetch.py
- Added `pages` key to `resource_collection` payload
- New functions to get page totals, next pages, previous pages, etc...
- Page link builder function
- Update resource_collection API View
- Total refactor of the front end resource collection required
- Update tests
=> Branks42 Pagination Collection

docs/api_endpoints.rst, docs/target_integration.rst, presqt/api_v1/urls.py, presqt/api_v1/views/collection/collection_job.py, presqt/api_v1/views/resource/resource_collection.py, presqt/api_v1/views/upload/upload_job.py, presqt/targets/curate_nd/classes/main.py, presqt/targets/curate_nd/functions/fetch.py, presqt/targets/figshare/functions/fetch.py, presqt/targets/figshare/utilities/get_figshare_project_data.py, presqt/targets/github/functions/fetch.py, presqt/targets/github/utilities/helpers/github_file_data.py, presqt/targets/gitlab/functions/fetch.py, presqt/targets/gitlab/utilities/get_gitlab_project_data.py, presqt/targets/osf/classes/main.py, presqt/targets/osf/functions/fetch.py, presqt/targets/zenodo/functions/fetch.py, presqt/targets/zenodo/utilities/helpers/fetch_helpers.py, presqt/utilities/__init__.py, presqt/utilities/utils/update_process_info.py
- Added process_info.json file for resource collection to keep track of request progression
- Updated all target fetch functions to update the process info file
- Updated relevant documentation
=> Progress Bar Collection

presqt/api_v1/tests/views/resource/test_resource.py, presqt/targets/curate_nd/tests/views/resource/test_resource_collection.py, presqt/targets/figshare/functions/fetch.py, presqt/targets/figshare/functions/keywords.py, presqt/targets/figshare/tests/views/resource/test_keywords.py, presqt/targets/figshare/tests/views/resource/test_resource.py, presqt/targets/figshare/tests/views/resource/test_resource_collection.py, presqt/targets/figshare/utilities/helpers/create_project.py, presqt/targets/github/functions/fetch.py, presqt/targets/github/tests/views/download/test_download.py, presqt/targets/github/tests/views/resource/test_resource.py, presqt/targets/github/tests/views/resource/test_resource_collection.py, presqt/targets/gitlab/functions/fetch.py, presqt/targets/gitlab/functions/keywords.py, presqt/targets/gitlab/tests/views/resource/test_resource.py, presqt/targets/gitlab/tests/views/resource/test_resource_collection.py, presqt/targets/osf/tests/views/resource/test_resource_collection.py, presqt/targets/osf/utilities/utils/get_page_numbers.py, presqt/targets/zenodo/tests/views/resource/test_resource_collection.py
- Update tests affected by resource_collection updates
=> Branks42 Pagination Test Updates

presqt/api_v1/utilities/utils/page_links.py, presqt/api_v1/utilities/validation/query_validator.py, presqt/api_v1/views/resource/resource_collection.py, presqt/targets/curate_nd/functions/fetch.py, presqt/targets/curate_nd/utilities/utils/get_page_numbers.py, presqt/targets/github/functions/fetch.py, presqt/targets/github/tests/views/resource/test_resource_collection.py, presqt/targets/gitlab/functions/fetch.py, presqt/targets/gitlab/tests/views/resource/test_resource_collection.py, presqt/targets/osf/functions/fetch.py, presqt/targets/osf/tests/views/resource/test_resource_collection.py
- Added pagination to search for each target
- Update tests
- N/A
=> Branks42 Search Pagination

presqt/api_v1/utilities/utils/page_links.py, presqt/targets/github/utilities/helpers/get_page_numbers.py
=> Added base page to the payload, tweak github func

presqt/targets/curate_nd/classes/base.py
- Squashed duplicate resources bug in CurateND
- N/A
=> Branks42 Curate Bug 2: Electric Boogaloo

presqt/api_v1/tests/views/transfer/test_transfer_job.py, presqt/api_v1/urls.py, presqt/api_v1/utilities/__init__.py, presqt/api_v1/utilities/utils/update_or_create_process_info.py, presqt/api_v1/views/job_status/job_status.py, presqt/api_v1/views/resource/resource_collection.py, presqt/targets/figshare/functions/download.py, presqt/targets/figshare/functions/fetch.py, presqt/targets/figshare/tests/views/resource/test_resource.py, presqt/targets/figshare/utilities/get_figshare_project_data.py, presqt/targets/github/tests/views/download/test_download.py, presqt/targets/github/utilities/helpers/get_page_numbers.py, presqt/targets/gitlab/functions/keywords.py, presqt/targets/gitlab/tests/views/download/test_download.py, presqt/targets/gitlab/tests/views/resource/test_keywords.py, presqt/targets/gitlab/tests/views/resource/test_resource.py, presqt/targets/osf/classes/main.py, presqt/targets/osf/tests/views/resource/test_keywords.py, presqt/targets/osf/tests/views/resource/test_resource.py, presqt/targets/zenodo/tests/views/resource/test_keywords.py, presqt/targets/zenodo/tests/views/resource/test_resource_collection.py, presqt/utilities/utils/update_process_info.py
- Added a singular Job endpoint
- Collection now writes to the Job folder
- Attempted to fix all tests
=> Job Consolidation

presqt/targets/figshare/functions/keywords.py, presqt/targets/figshare/tests/views/resource/test_keywords.py, presqt/targets/github/functions/keywords.py, presqt/targets/github/tests/views/resource/test_keywords.py, presqt/targets/gitlab/functions/keywords.py, presqt/targets/gitlab/tests/views/resource/test_keywords.py, presqt/targets/osf/functions/keywords.py, presqt/targets/osf/tests/views/resource/test_keywords.py
- Made keyword error messages more clear to the end user
- N/A
=> Branks42 Keyword Messages

presqt/api_v1/utilities/validation/structure_validation.py
=> Added clarifying message for transfer error

presqt/management/commands/delete_outdated_mediafiles.py, presqt/management/tests/commands/test_delete_outdated_mediafiles.py
- Updated management command for new process_info format
- N/A
=> Branks42 Mediafiles Update

presqt/api_v1/views/resource/base_resource.py, presqt/targets/curate_nd/functions/download.py, presqt/targets/figshare/functions/download.py, presqt/targets/github/functions/download.py, presqt/targets/github/utilities/helpers/download_content.py, presqt/targets/gitlab/functions/download.py, presqt/targets/osf/functions/download.py, presqt/utilities/__init__.py, presqt/utilities/utils/update_process_info.py
- Added messages for each step of the DL process
- N/A
=> Branks42 Messages for DL Process

docs/code_documentation.rst, docs/target_integration.rst, presqt/api_v1/views/job_status/job_status.py, presqt/api_v1/views/resource/base_resource.py, presqt/targets/figshare/functions/upload.py, presqt/targets/figshare/tests/views/resource/test_resource.py, presqt/targets/github/functions/upload.py, presqt/targets/github/tests/views/resource/test_resource.py, presqt/targets/gitlab/functions/upload.py, presqt/targets/gitlab/tests/views/resource/test_resource_collection.py, presqt/targets/osf/classes/storage_folder.py, presqt/targets/osf/functions/upload.py, presqt/targets/osf/tests/views/resource/test_resource.py, presqt/targets/utilities/__init__.py, presqt/targets/utilities/tests/shared_upload_test_functions.py, presqt/targets/utilities/utils/upload_total_files.py, presqt/targets/zenodo/functions/upload.py, presqt/targets/zenodo/tests/views/resource/test_resource_collection.py
- Update target functions to increment progress with each uploaded file
- Updated BaseResource
- Update tests
- Update docs
- N/A
=> Branks42 Upload Progress

presqt/api_v1/views/job_status/job_status.py, presqt/api_v1/views/resource/base_resource.py, presqt/api_v1/views/resource/resource.py, presqt/targets/curate_nd/classes/main.py, presqt/targets/curate_nd/functions/download.py, presqt/targets/figshare/functions/download.py, presqt/targets/figshare/functions/upload.py, presqt/targets/figshare/utilities/get_figshare_project_data.py, presqt/targets/github/functions/download.py, presqt/targets/github/functions/upload.py, presqt/targets/github/utilities/helpers/download_content.py, presqt/targets/github/utilities/helpers/github_file_data.py, presqt/targets/gitlab/functions/download.py, presqt/targets/gitlab/functions/upload.py, presqt/targets/gitlab/utilities/get_gitlab_project_data.py, presqt/targets/osf/classes/main.py, presqt/targets/osf/classes/storage_folder.py, presqt/targets/osf/functions/download.py, presqt/targets/osf/functions/upload.py, presqt/targets/zenodo/functions/download.py, presqt/targets/zenodo/functions/upload.py, presqt/targets/zenodo/utilities/helpers/fetch_helpers.py, presqt/utilities/__init__.py, presqt/utilities/utils/update_process_info.py
- Refactor upload/download functions
- Add percentages to payload
- New messages for each step of process
***Still To Do***
- Update tests
=> Branks42 Transfer Progress

presqt/api_v1/views/job_status/job_status.py, presqt/api_v1/views/resource/resource_collection.py
- Made slight tweak for use case where user has no resources
- N/A
=> Branks42 Collection Status

docs/api_endpoints.rst, docs/target_integration.rst, docs/user_notes.rst, docs/web_services.rst, presqt/targets/osf/functions/download.py, presqt/targets/osf/functions/upload.py
- Refactored 'API Endpoint' section of docs by adding job status endpoints
- Added Figshare to some documentation
=> Documentation Update

presqt/targets/osf/functions/fetch.py
=> Change from string to None

presqt/api_v1/views/job_status/job_status.py
- Update upload/transfer job payloads for consistency
- N/A
=> Branks42 Update Payloads

presqt/api_v1/utilities/utils/multiple_process_check.py, presqt/api_v1/views/resource/base_resource.py, presqt/api_v1/views/resource/resource.py, presqt/targets/osf/tests/views/resource/test_resource.py
- We want to limit users to having one subprocess running at a time
- New function to check if a user currently has an action in progress
- Raise error response on API endpoints if they do
- N/A
=> Branks42 Multiple Calls

docs/api_endpoints.rst, presqt/api_v1/views/resource/base_resource.py, presqt/api_v1/views/resource/resource.py
- Update documentation with multiple process error messages
- N/A
=> Branks42 Multiple Process Doc Updates

docs/api_endpoints.rst, docs/target_integration.rst, presqt/api_v1/serializers/target.py, presqt/api_v1/tests/views/target/test_target.py, presqt/json_schemas/target_schema.json, presqt/specs/targets.json
- Added `token_url` to targets.json, schema and serializers
- Update docs
- N/A
=> Branks42  token links

presqt/api_v1/tests/views/job_status/test_download_job.py, presqt/api_v1/views/resource/base_resource.py, presqt/targets/figshare/tests/views/download/test_download.py, presqt/targets/github/tests/views/download/test_download.py, presqt/targets/gitlab/tests/views/download/test_download.py, presqt/targets/osf/tests/views/resource/test_resource.py, presqt/targets/utilities/tests/shared_download_test_functions.py, presqt/targets/zenodo/tests/views/download/test_download.py
- Refactored where fixity_info.json and PRESQT_FTS_METADATA.json are stored in the bag when downloading
- Updated appropriate tests and documentation
=> Download Bug

config/settings/base.py, config/settings/production.py, config/settings/qa.py, docker-compose.yml, docs/api_endpoints.rst, presqt/api_v1/tests/views/job_status/test_download_job.py, presqt/api_v1/tests/views/job_status/test_transfer_job.py, presqt/api_v1/tests/views/job_status/test_upload_job.py, presqt/api_v1/tests/views/resource/test_resource.py, presqt/api_v1/utilities/__init__.py, presqt/api_v1/utilities/utils/send_email.py, presqt/api_v1/utilities/validation/email_validation.py, presqt/api_v1/views/resource/base_resource.py, presqt/api_v1/views/resource/resource.py, presqt/targets/figshare/tests/views/download/test_download.py, presqt/targets/figshare/tests/views/resource/test_resource.py, presqt/targets/github/tests/views/download/test_download.py, presqt/targets/github/tests/views/resource/test_resource.py, presqt/targets/github/tests/views/resource/test_resource_collection.py, presqt/targets/gitlab/tests/views/download/test_download.py, presqt/targets/gitlab/tests/views/resource/test_resource.py, presqt/targets/gitlab/tests/views/resource/test_resource_collection.py, presqt/targets/osf/tests/views/resource/test_resource.py, presqt/targets/zenodo/tests/views/download/test_download.py, presqt/targets/zenodo/tests/views/resource/test_resource_collection.py
- Created email functions for different actions
- Added EMAIL information to settings files
- New env variable
- New tests
- Updated old tests to include `presqt-email-opt-in` header
- N/A
=> Bbois Email

config/settings/base.py, presqt/api_v1/utilities/utils/send_email.py, presqt/api_v1/views/resource/base_resource.py
- Provides user with more details about the action that occurred
- N/A
=> New Email Messages

docs/web_services.rst, presqt/api_v1/utilities/__init__.py, presqt/api_v1/utilities/keyword_enhancement/automatic_keywords.py, presqt/api_v1/utilities/keyword_enhancement/fetch_ontologies.py, presqt/api_v1/utilities/keyword_enhancement/manual_keywords.py, presqt/api_v1/utilities/keyword_enhancement/update_targets_keywords.py, presqt/api_v1/utilities/utils/keyword_enhancer.py, presqt/api_v1/utilities/validation/keyword_post_validation.py, presqt/api_v1/views/resource/base_resource.py, presqt/api_v1/views/resource/resource_keywords.py, presqt/json_schemas/metadata_schema.json, presqt/targets/figshare/tests/views/resource/test_keywords.py, presqt/targets/github/functions/keywords.py, presqt/targets/github/tests/views/resource/test_keywords.py, presqt/targets/gitlab/tests/views/resource/test_keywords.py, presqt/targets/osf/tests/views/resource/test_keywords.py, presqt/targets/zenodo/tests/views/resource/test_keywords.py
- Added ontologies to keyword metadata
- Updated and added keyword functions
- Updated tests
- Updated docs
- N/A
=> Bbois Keyword Ontologies

presqt/targets/github/utilities/helpers/github_paginated_data.py
- Collection now sorted by most recently updated
- N/A
=> GitHub Bug Fix

docs/service_endpoints.rst, docs/services.rst, presqt/api_v1/views/service/fairshare/evaluator.py
- Added FAIRshare documentation
- N/A
=> Doc Updates

presqt/targets/github/functions/upload.py, presqt/targets/utilities/utils/duplicate_titles.py
- Duplicate title code now working properly
- N/A
=> Squash Bug in Duplicate Title Code

presqt/api_v1/tests/views/job_status/test_transfer_job.py, presqt/api_v1/utilities/keyword_enhancement/update_targets_keywords.py, presqt/api_v1/utilities/validation/keyword_action_validation.py, presqt/api_v1/views/resource/base_resource.py, presqt/json_schemas/metadata_schema.json
- New `none` option for `presqt-keyword-action` during transfer
- New test
- Fix bug in `metadata_schema.json`
- Add `none` option to front end transfer modal
=> Branks42 Transfer Keywords Optional

presqt/api_v1/utilities/keyword_enhancement/automatic_keywords.py, presqt/api_v1/utilities/keyword_enhancement/manual_keywords.py, presqt/api_v1/utilities/utils/keyword_enhancer.py, presqt/targets/github/functions/keywords.py
- Keywords are no longer case sensitive. They default all keywords to lower case.
=> Keyword Lower

presqt/api_v1/utilities/utils/send_email.py, presqt/api_v1/utilities/validation/fairshare_validation.py, presqt/api_v1/views/resource/base_resource.py, presqt/api_v1/views/service/fairshare/evaluator.py
- Allow users to receive an email when FAIR process is complete
- Update `email_blaster`
- N/A
=> Email on FAIR completion

presqt/api_v1/utilities/utils/keyword_enhancer.py
- Fixed bug where enhanced keywords included already existing source keywords
- N/A
=> Branks42 Keyword Duplicate Bug

config/settings/base.py, presqt/api_v1/utilities/utils/send_email.py, presqt/api_v1/views/resource/base_resource.py, presqt/api_v1/views/service/fairshare/evaluator.py, presqt/templates/emails/download_email.html, presqt/templates/emails/fair_email.html, presqt/templates/emails/transfer_email.html, presqt/templates/emails/upload_email.html, requirements/base.txt
- Emails from PresQT are now formatted nicely as we head towards QA testing
- New templates
- Update `email_blaster` func
- Rebuild docker container (New requirement)
OLD
NEW
=> Branks42 Email Templates

docs/api_endpoints.rst, presqt/api_v1/tests/views/job_status/test_transfer_job.py, presqt/api_v1/utilities/__init__.py, presqt/api_v1/utilities/validation/fairshare_evaluator_validation.py, presqt/api_v1/views/job_status/job_status.py, presqt/api_v1/views/resource/base_resource.py, presqt/templates/emails/transfer_email.html
- Opt in option for fairshare evaluator on transfer
- Update email template for transfer
- Update tests
- N/A
=> BBois Fair Transfer

config/nginx/nginx.conf, config/settings/base.py, presqt/api_v1/__init__.py, presqt/api_v1/views/bag_and_zip/bag_and_zip.py, presqt/api_v1/views/job_status/job_status.py, presqt/api_v1/views/resource/base_resource.py, presqt/api_v1/views/resource/resource.py, presqt/api_v1/views/resource/resource_collection.py, presqt/api_v1/views/resource/resource_keywords.py, presqt/api_v1/views/service/eaasi/download.py, presqt/api_v1/views/service/eaasi/proposal.py, presqt/api_v1/views/service/fairshare/evaluator.py, presqt/api_v1/views/service/service.py, presqt/api_v1/views/status/status.py, presqt/api_v1/views/target/target.py
- Upgraded Django
- X-Frame-Options no longer set Multiple Times
- Removed DRF templates for API endpoints to resolve "No anti-CSRF token for some URIs"
- Web Service now Configured to Hide Software Identity and Version
=> Security fixes

docs/target_integration.rst, presqt/api_v1/utilities/depth_helpers/finite_depth_upload.py, presqt/api_v1/utilities/metadata/create_fts_metadata.py, presqt/api_v1/utilities/metadata/upload_metadata.py, presqt/api_v1/views/resource/base_resource.py, presqt/json_schemas/metadata_schema.json, presqt/targets/curate_nd/functions/download.py, presqt/targets/curate_nd/utilities/__init__.py, presqt/targets/curate_nd/utilities/utils/extra_metadata_helper.py, presqt/targets/figshare/functions/download.py, presqt/targets/figshare/utilities/helpers/extra_metadata_helper.py, presqt/targets/github/functions/download.py, presqt/targets/github/utilities/__init__.py, presqt/targets/github/utilities/helpers/extra_metadata_helper.py, presqt/targets/github/utilities/helpers/validation_check.py, presqt/targets/gitlab/functions/download.py, presqt/targets/gitlab/utilities/__init__.py, presqt/targets/gitlab/utilities/extra_metadata_helper.py, presqt/targets/osf/functions/download.py, presqt/targets/osf/utilities/__init__.py, presqt/targets/osf/utilities/utils/extra_metadata_helper.py, presqt/targets/zenodo/functions/download.py, presqt/targets/zenodo/utilities/__init__.py, presqt/targets/zenodo/utilities/helpers/extra_metadata_helper.py
- Added extra metadata to all target download functions
- Each target has their own `extra_metadata_helper` function
- Update JSONschema for metadata
- Update create_fts_metadata func and calls to include extra metadata
- This key will be overwritten to always have the latest information
- Update documentation for resource download
- Tests need to be fixed, unrelated to this PR. Some still seem to be outdated
=> Branks42 Optional Extra Metadata

presqt/api_v1/views/job_status/job_status.py, presqt/api_v1/views/resource/base_resource.py
- Added links to uploaded/transferred resources in job_status payload
- N/A
=> Branks42 Links in Payload

presqt/api_v1/views/service/fairshake/assessment.py
- Assessments must be published for users to access the insignia svgs
=> Branks42 Publish FAIRshake Assessment

presqt/api_v1/views/service/fairshake/assessment.py
- Better (see: existent) handling of FAIRshake errors
- N/A
=> FAIRshake Error Handling

docs/_static/css/custom.css, docs/conf.py
=> Wrap the tables aka clean up docs

presqt/api_v1/utilities/validation/fairshake_request_validator.py, presqt/api_v1/views/service/fairshake/assessment.py, presqt/specs/services/fairshake/fairshake_test_fetch.json
- PresQT FAIRshake integration now uses custom PresQT rubrics
- N/A
=> Branks42 FAIRshake use PresQT Rubrics

presqt/api_v1/utilities/validation/fairshake_assessment_validator.py, presqt/api_v1/utilities/validation/fairshake_request_validator.py, presqt/api_v1/views/service/fairshake/assessment.py, presqt/specs/services/fairshake/fairshake_test_fetch.json, presqt/specs/services/fairshake/fairshare_fairshake_helper.json
- Utilize existing tests we run in FAIRshare and translate them into a PresQT rubric
- New rubric id to use on these endpoints is `96`
- Update validation functions
- New helper json file to translate FAIRshare metrics to FAIRshake metrics
- N/A
=> Branks42  FAIRshake Automatic

presqt/targets/curate_nd/classes/main.py, presqt/targets/utilities/utils/async_functions.py
- Hotfix for Curate returning a 502 error
- N/A
=> Curate Hotfix

presqt/targets/zenodo/functions/upload.py, presqt/targets/zenodo/utilities/upload_extra_metadata.py
=> Dev -> Master

presqt/targets/zenodo/utilities/upload_extra_metadata.py
- Create new `docker-compose-development.yml` file for outside developers
- Bump Django
=> Develop -> Master
